services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma

  frontend:
    build:
      context: ./frontend
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_INTERNAL_URL: http://backend:4000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
